services:
  - type: web
    name: cameratd
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: node backend/index.js
    envVars:
      - key: NODE_VERSION
        value: "22"
